apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
  namespace: bankapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
        - name: bankapp
          image: hamza426/bankapp:6
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL  # Changed from spring.datasource.url
              valueFrom:
                configMapKeyRef:
                  name: bankapp-config
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME  # Changed from spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: bankapp-secret
                  key: spring.datasource.username
            - name: SPRING_DATASOURCE_PASSWORD  # Changed from spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: bankapp-secret
                  key: spring.datasource.password
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"